# Generated by Django 4.2.1 on 2023-05-25 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['level_id'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=1000, null=True)),
                ('chinese_title', models.TextField(max_length=1000, null=True)),
                ('bg_image', models.URLField(max_length=1000)),
                ('textfile', models.TextField(max_length=1000, null=True)),
                ('audiofile', models.URLField(max_length=1000)),
                ('audio_bg_image', models.URLField(max_length=1000, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('level_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chinese_folktales_website.level')),
            ],
            options={
                'ordering': ['story_id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chinese_folktales_website.story')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['story_id'],
            },
        ),
    ]
